### PR TITLE
Improve consistency of layout sections

### LINKED ISSUE #125: Binary prefix usage in prose
Is there any precedent for adding a prefix such as `0b` to indicate that a number is presented in binary? There are a handful of places where I could see this making sense, for example in section 5.6

```
   var:
      The 2 bit variant field as defined by Section 4.1 set to 10.
      Occupies bits 64 and 65 of octet 8.
```

I would find it more clear to see `set to 0b10`, confirming the value to be a decimal 2 rather than decimal 10.

### PR DESCRIPTION
**Pull request by tgross35**
- Add '0b' binary prefix where fitting
- Add decimal values in addition to binary where it makes sense
- Add "occupies bits..." where needed to make more consistent
- Match capitalization of "octet" and terminal punctuation

Fixes #125

### CODE REVIEW

**Comment by kyzer-davis** [comment]
I see a few other places where we can add `0b`, let me get those in another commit.

**Comment by kyzer-davis** [comment]
Okay, I should have hit all of the 0b items, a few 0x items I saw along the way.

I went ahead and added `Occupies bits ... octets ...` text to every bit layout descriptor in v1-v8 since it was bugging me that now only a few had them and some others did not. 

I will leave this open this week so others can double check the edits. 
Specifically I ask: check the bits/octets referenced are correct. They look correct to me but little things like this can lead to erratas filed later.

**Comment by danielmarschall** [comment]
Is the term "variant 10x" correct, or should it be "variant 0b10x"?

**Comment by kyzer-davis** [comment]
> Is the term "variant 10x" correct, or should it be "variant 0b10x"?

I wrote it that way in one pass but didn't like the way it read since the `x` is in there. I decided to leave it as 10x vs 0b01x which IMO looks a bit uglier.

**Comment by kyzer-davis** [comment]
Update: GENART review also confirmed this consistency with the underlying field definitions should be done.
I will merge it down tomorrow if there are no objections.

**Pull request merged**
